### ISSUE TITLE
Feature request: option to disable automatic popup of next word.

### ISSUE THREAD

**Issue by leotaku** [ncm2/ncm2-bufword#4]
I personally used the ncm1 buffer word completion to get some keyword completion for languages that do not have semantic completion support. While the automatic popup can be helpful sometimes, more often than not it simply irritates me. An option to disable this feature would be great.

Thank you for your hard work on ncm/ncm2!

**Comment by roxma** [comment]
Try `call ncm2#override_source('bufword', {'on_completed': 0})` for now

**Comment by leotaku** [comment]
Thank you, this worked perfectly!

**Comment by roxma** [comment]
The automatic popup of next word feature has been removed. I notice that I have never used this feature after months. https://github.com/ncm2/ncm2-bufword/commit/183843100999d021e5d52c09c61faa6c64ac6e2f
